### PR TITLE
Apply V8 optimization on Node V8 as well (instead of on V10 and higher).

### PR DESCRIPTION
**Pull request by KurtPattyn**
See sonic-boom issue https://github.com/mcollina/sonic-boom/issues/19 for more information.

### CODE REVIEW

**Comment by davidmarkclements** [comment]
Cool! So there’s some history here - I disabled for Node 8 because at the time it was failing on that version of 8 

I can’t remember whether it was an intermittent failure or just failing on specific minor versions. 

Ideally we need to check this with every minor patch version on 8 but even then I’m hesitant because of the possibility of non-deterministic failure (which again I’m not sure of - @mcollina do you remember anything about that?) 

We can do this but release as a major becaue of possible breaking changes for some versions/scenarios on node 8 - at least then any current dependents won’t be hit

**Comment by mcollina** [comment]
I think everything is already protected with a try-catch, I'm +1 in landing this.

**Comment by davidmarkclements** [comment]
ah no, I think what it was is in older version of Node 8 %FlattenString actually came out worse perf wise, but I don't think that's a big issue any more - merging

**Comment by davidmarkclements** [comment]
thanks @KurtPattyn released as v1.0.9

**Pull request merged**
